name: get_me_there
description: A Flutter application to have weather and public transport info

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.3
  http: ^0.12.0+2
  flutter_spinkit: ^4.0.0
  flutter_google_places: ^0.2.3
  google_maps_flutter: ^0.5.21+3
  flutter_map: ^0.7.2
  google_maps_webservice: ^0.0.14
  connectivity: ^0.4.4
  provider: ^3.1.0
  location: ^2.3.5
  geocoder: ^0.2.1
  uuid: ^2.0.2
  timeline_list: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

fonts:
  - family: Rubik
    fonts:
      - asset: fonts/Rubik-Regular.ttf
      - asset: fonts/Rubik-Medium.ttf
        weight: 500